spring:
  profiles:
    active: local
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # PostgreSQL? ?? Hibernate ?? ??
        format_sql: true
    hibernate:
      ddl-auto: update
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/suadoosic;MODE=PostgreSQL # PostgreSQL ?? ??? ??
      username: sa
      password:
      driver-class-name: org.h2.Driver
logging:
  level:
    com:
      querydsl:
        sql: DEBUG
